name: CI/CD for Search Online Movie

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Deploy to Hostinger
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOSTNAME }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.SSH_HOSTINGER_KEY_MOVIE }}
        script: |
          cd /build
          git pull origin main
          # Copy build files to your hosting directory
